/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Parameters */

#ifndef _Included_jni_Parameters
#define _Included_jni_Parameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Parameters
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jni_Parameters_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_Parameters
 * Method:    isHigherThan
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jni_Parameters_isHigherThan
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
